services:
  server6_tp3_readonly_db:
    image: postgres:16
    container_name: server6_tp3_readonly_db
    environment:
      POSTGRES_DB: tp3_readonly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - server6_tp3_readonly_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  server6_tp3_readonly_data:
